In this notebook, you will learn how to manipulate data with Pytorch  
Let's start by importing Pytorch

In [1]:
import torch

## Basic tensor operation

In [2]:
tensor = torch.rand((4, 3, 2))
tensor

tensor([[[0.8517, 0.0224],
         [0.4806, 0.1850],
         [0.5783, 0.9709]],

        [[0.9068, 0.3999],
         [0.8939, 0.6506],
         [0.0603, 0.6700]],

        [[0.1521, 0.7732],
         [0.4085, 0.5179],
         [0.3226, 0.3971]],

        [[0.6273, 0.4716],
         [0.4984, 0.1449],
         [0.9767, 0.8813]]])

Display the size of the produced tensor

In [3]:
tensor.shape 

torch.Size([4, 3, 2])

Give the total number of elements inside the tensor

In [4]:
tensor.numel()

24

Change the shape of the tensor into a 4x6 tensor

In [5]:
reshaped = tensor.reshape(4,6)
reshaped.shape

torch.Size([4, 6])

Transform a python list into a tensor

In [6]:
list_to_transform = [[9, 8, 7], [4, 5, 6], [3, 2, 1]]
tensor_2 = torch.tensor(list_to_transform)
print(type(tensor_2))
tensor_2

<class 'torch.Tensor'>


tensor([[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]])

## Operations on tensor

In [7]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

Add 3 to every element of the tensor, put the result in a new tensor

In [22]:
y = torch.add(x,3)
# or y = x + 3
y

tensor([3, 4, 5, 6])

Multiply by 3 the tensor x, put the result in a new tensor

In [23]:
y = torch.multiply(x,3)
# or y = x * 3
y

tensor([0, 3, 6, 9])

Put every element of x to the power of 3

In [24]:
y = torch.pow(x,3)
# or y = x ** 3
y

tensor([ 0,  1,  8, 27])

Multiply x with k

In [25]:
k = torch.Tensor([8, 7, 5, 1])

y = torch.multiply(x,k)
# or y = x * k
y 

tensor([ 0.,  7., 10.,  3.])

Makes x to the power of k

Put every element of x to exponential

In [13]:
y = torch.exp(x)
y

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

Perform the element wise product of `a` and `b`

In [28]:
a = torch.rand((5))
b = torch.rand((5))
y = torch.mul(a,b)
y

tensor([0.0239, 0.1739, 0.5379, 0.1466, 0.3274])

Perform the dot product of `a` and `b`

In [15]:
y = torch.dot(a,b)
y

tensor(0.8645)

Sum along the column axis of `l`

In [16]:
l = torch.rand((5, 3, 6))
print(l)
l.sum(dim =1)

tensor([[[0.5227, 0.1054, 0.8007, 0.8091, 0.5861, 0.6664],
         [0.1281, 0.3808, 0.9796, 0.8966, 0.8591, 0.9461],
         [0.4851, 0.1908, 0.6734, 0.8816, 0.3707, 0.4657]],

        [[0.6523, 0.2684, 0.2473, 0.5828, 0.5473, 0.7464],
         [0.0574, 0.0312, 0.3352, 0.2333, 0.7094, 0.7446],
         [0.1110, 0.7576, 0.8916, 0.2751, 0.7878, 0.1662]],

        [[0.7806, 0.2382, 0.5550, 0.7290, 0.4472, 0.8703],
         [0.1191, 0.2185, 0.2875, 0.3106, 0.7949, 0.0186],
         [0.6112, 0.0364, 0.8965, 0.0591, 0.9203, 0.0336]],

        [[0.2257, 0.8931, 0.2988, 0.3231, 0.3475, 0.3717],
         [0.9123, 0.6383, 0.5415, 0.0125, 0.8087, 0.6125],
         [0.4584, 0.0466, 0.2340, 0.9710, 0.8993, 0.3973]],

        [[0.8669, 0.6505, 0.4698, 0.6672, 0.8255, 0.3778],
         [0.8268, 0.2383, 0.4974, 0.1645, 0.8827, 0.5735],
         [0.3714, 0.7148, 0.5580, 0.0220, 0.3776, 0.9987]]])


tensor([[1.1360, 0.6770, 2.4536, 2.5873, 1.8159, 2.0782],
        [0.8207, 1.0573, 1.4741, 1.0912, 2.0445, 1.6571],
        [1.5109, 0.4930, 1.7390, 1.0987, 2.1624, 0.9225],
        [1.5964, 1.5780, 1.0744, 1.3067, 2.0556, 1.3814],
        [2.0650, 1.6036, 1.5253, 0.8537, 2.0858, 1.9500]])

## Slicing

Display the 3 last element of x

In [17]:
x[-3:]

tensor([1, 2, 3])

Display the last element of x

In [18]:
x[-1]

tensor(3)

Display the element of m, by step of 2

In [19]:
m = torch.arange(18)
m[:-1:2]

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

Print only the first 2 rows of `matrix`

In [20]:
matrix = torch.rand((6, 4, 2)) # it doesn't look like matrix, I think it is more tensor...
print(f'for checking (the whole tensor)\n{matrix}\n')
matrix[:,0:2,:]

for checking (the whole tensor)
tensor([[[0.7371, 0.7912],
         [0.1875, 0.6335],
         [0.1838, 0.7980],
         [0.1981, 0.0513]],

        [[0.7245, 0.6494],
         [0.8803, 0.1527],
         [0.0210, 0.0328],
         [0.3844, 0.2838]],

        [[0.4999, 0.2355],
         [0.2708, 0.9732],
         [0.7198, 0.2561],
         [0.9926, 0.6237]],

        [[0.8415, 0.1582],
         [0.4673, 0.5572],
         [0.5415, 0.0373],
         [0.7770, 0.7930]],

        [[0.0388, 0.3977],
         [0.6751, 0.1986],
         [0.2047, 0.3955],
         [0.9486, 0.4905]],

        [[0.4081, 0.6483],
         [0.5348, 0.1476],
         [0.7311, 0.4836],
         [0.4148, 0.7410]]])



tensor([[[0.7371, 0.7912],
         [0.1875, 0.6335]],

        [[0.7245, 0.6494],
         [0.8803, 0.1527]],

        [[0.4999, 0.2355],
         [0.2708, 0.9732]],

        [[0.8415, 0.1582],
         [0.4673, 0.5572]],

        [[0.0388, 0.3977],
         [0.6751, 0.1986]],

        [[0.4081, 0.6483],
         [0.5348, 0.1476]]])

Now, only print the first 2 columns of `matrix`

In [21]:
# if I understand it right, because I am not sure what means first 2 row, if tensor has only 2 column
matrix[:,:,0:2]

tensor([[[0.7371, 0.7912],
         [0.1875, 0.6335],
         [0.1838, 0.7980],
         [0.1981, 0.0513]],

        [[0.7245, 0.6494],
         [0.8803, 0.1527],
         [0.0210, 0.0328],
         [0.3844, 0.2838]],

        [[0.4999, 0.2355],
         [0.2708, 0.9732],
         [0.7198, 0.2561],
         [0.9926, 0.6237]],

        [[0.8415, 0.1582],
         [0.4673, 0.5572],
         [0.5415, 0.0373],
         [0.7770, 0.7930]],

        [[0.0388, 0.3977],
         [0.6751, 0.1986],
         [0.2047, 0.3955],
         [0.9486, 0.4905]],

        [[0.4081, 0.6483],
         [0.5348, 0.1476],
         [0.7311, 0.4836],
         [0.4148, 0.7410]]])